<?php    // Turn on debugging level    $Vtiger_Utils_Log = true;    include_once('vtlib/Vtiger/Menu.php');    include_once('vtlib/Vtiger/Module.php');        // Create module instance and save it first    $module = new Vtiger_Module();    $module->name = 'XActivity';	$module->parent ='Tools';    $module->save();    $module->initWebservice();        // Initialize all the tables required    $module->initTables();    /**    * Creates the following table:    * vtiger_payslip (payslipid INTEGER)    * vtiger_payslipcf(payslipid INTEGER PRIMARY KEY)    * vtiger_payslipgrouprel((payslipid INTEGER PRIMARY KEY, groupname VARCHAR(100))    */        // Add the module to the Menu (entry point from UI)    $menu = Vtiger_Menu::getInstance('Tools');    $menu->addModule($module); 
	$block_0_ = new Vtiger_Block();	$block_0_->label = 'General Information';	$module->addBlock($block_0_);
				$field_block_0_field_0 = new Vtiger_Field();				$field_block_0_field_0->label = 'Created Time';				$field_block_0_field_0->name = 'CreatedTime';				$field_block_0_field_0->table = 'vtiger_crmentity';				$field_block_0_field_0->column = 'createdtime';				$field_block_0_field_0->uitype = 70; 				$field_block_0_field_0->typeofdata = 'T~O';				$field_block_0_field_0->displaytype = 2;				$block_0_->addField($field_block_0_field_0); 			
				$field_block_0_field_1 = new Vtiger_Field();				$field_block_0_field_1->label = 'Modified Time';				$field_block_0_field_1->name = 'ModifiedTime';				$field_block_0_field_1->table = 'vtiger_crmentity';				$field_block_0_field_1->column = 'modifiedtime';				$field_block_0_field_1->uitype = 70; 				$field_block_0_field_1->typeofdata = 'T~O';				$field_block_0_field_1->displaytype = 2;				$block_0_->addField($field_block_0_field_1); 			
				$field_block_0_field_2 = new Vtiger_Field();				$field_block_0_field_2->label = 'Assigned To';				$field_block_0_field_2->name = 'assigned_user_id';				$field_block_0_field_2->table = 'vtiger_crmentity';				$field_block_0_field_2->column = 'smownerid';				$field_block_0_field_2->uitype = 53; 				$field_block_0_field_2->typeofdata = 'V~M';				$block_0_->addField($field_block_0_field_2); 			
				$field_block_0_field_3 = new Vtiger_Field();				$field_block_0_field_3->label = 'CRM No';				$field_block_0_field_3->name = 'z_ac_crmno';				$field_block_0_field_3->column = 'z_ac_crmno';				$field_block_0_field_3->columntype = 'VARCHAR(100)';				$field_block_0_field_3->uitype = 4; 				$field_block_0_field_3->typeofdata = 'V~O';				$block_0_->addField($field_block_0_field_3); 			
				$module->setEntityIdentifier($field_block_0_field_3);				
				$field_block_0_field_4 = new Vtiger_Field();				$field_block_0_field_4->label = 'Workplan';				$field_block_0_field_4->name = 'z_ac_workplan';				$field_block_0_field_4->column = 'z_ac_workplan';				$field_block_0_field_4->columntype = 'VARCHAR(20)';				$field_block_0_field_4->uitype = 10; 				$field_block_0_field_4->typeofdata = 'V~M';				$block_0_->addField($field_block_0_field_4); 				$field_block_0_field_4->setRelatedModules(Array('XWorkplan'));			
				$field_block_0_field_5 = new Vtiger_Field();				$field_block_0_field_5->label = 'Start Time';				$field_block_0_field_5->name = 'z_ac_starttime';				$field_block_0_field_5->column = 'z_ac_starttime';				$field_block_0_field_5->columntype = 'VARCHAR(100)';				$field_block_0_field_5->uitype = 1; 				$field_block_0_field_5->typeofdata = 'V~M~LE~100';				$block_0_->addField($field_block_0_field_5); 			
				$field_block_0_field_6 = new Vtiger_Field();				$field_block_0_field_6->label = 'End Time';				$field_block_0_field_6->name = 'z_ac_endtime';				$field_block_0_field_6->column = 'z_ac_endtime';				$field_block_0_field_6->columntype = 'VARCHAR(100)';				$field_block_0_field_6->uitype = 1; 				$field_block_0_field_6->typeofdata = 'V~M~LE~100';				$block_0_->addField($field_block_0_field_6); 			
				$field_block_0_field_7 = new Vtiger_Field();				$field_block_0_field_7->label = 'Latitude';				$field_block_0_field_7->name = 'z_ac_latitude';				$field_block_0_field_7->column = 'z_ac_latitude';				$field_block_0_field_7->columntype = 'DECIMAL(16,12)';				$field_block_0_field_7->uitype = 7; 				$field_block_0_field_7->typeofdata = 'NN~O~3,12';				$block_0_->addField($field_block_0_field_7); 			
				$field_block_0_field_8 = new Vtiger_Field();				$field_block_0_field_8->label = 'Longitude';				$field_block_0_field_8->name = 'z_ac_longitude';				$field_block_0_field_8->column = 'z_ac_longitude';				$field_block_0_field_8->columntype = 'DECIMAL(16,12)';				$field_block_0_field_8->uitype = 7; 				$field_block_0_field_8->typeofdata = 'NN~O~3,12';				$block_0_->addField($field_block_0_field_8); 			
				$field_block_0_field_9 = new Vtiger_Field();				$field_block_0_field_9->label = 'Objective';				$field_block_0_field_9->name = 'z_ac_objective';				$field_block_0_field_9->column = 'z_ac_objective';				$field_block_0_field_9->columntype = 'TEXT';				$field_block_0_field_9->uitype = 21; 				$field_block_0_field_9->typeofdata = 'V~M';				$block_0_->addField($field_block_0_field_9); 			
				$field_block_0_field_10 = new Vtiger_Field();				$field_block_0_field_10->label = 'Notes';				$field_block_0_field_10->name = 'z_ac_notes';				$field_block_0_field_10->column = 'z_ac_notes';				$field_block_0_field_10->columntype = 'TEXT';				$field_block_0_field_10->uitype = 21; 				$field_block_0_field_10->typeofdata = 'V~M';				$block_0_->addField($field_block_0_field_10); 			
				$field_block_0_field_11 = new Vtiger_Field();				$field_block_0_field_11->label = 'Highlights';				$field_block_0_field_11->name = 'z_ac_highlights';				$field_block_0_field_11->column = 'z_ac_highlights';				$field_block_0_field_11->columntype = 'TEXT';				$field_block_0_field_11->uitype = 21; 				$field_block_0_field_11->typeofdata = 'V~O';				$block_0_->addField($field_block_0_field_11); 			
				$field_block_0_field_12 = new Vtiger_Field();				$field_block_0_field_12->label = 'Next Steps';				$field_block_0_field_12->name = 'z_ac_nextsteps';				$field_block_0_field_12->column = 'z_ac_nextsteps';				$field_block_0_field_12->columntype = 'TEXT';				$field_block_0_field_12->uitype = 21; 				$field_block_0_field_12->typeofdata = 'V~O';				$block_0_->addField($field_block_0_field_12); 			
				$field_block_0_field_13 = new Vtiger_Field();				$field_block_0_field_13->label = 'Follow-up Commitment Date';				$field_block_0_field_13->name = 'z_ac_followupcomdate';				$field_block_0_field_13->column = 'z_ac_followupcomdate';				$field_block_0_field_13->columntype = 'DATE';				$field_block_0_field_13->uitype = 5; 				$field_block_0_field_13->typeofdata = 'D~O';				$block_0_->addField($field_block_0_field_13); 			
				$field_block_0_field_14 = new Vtiger_Field();				$field_block_0_field_14->label = 'Activity Type';				$field_block_0_field_14->name = 'z_ac_activitytype';				$field_block_0_field_14->column = 'z_ac_activitytype';				$field_block_0_field_14->columntype = 'VARCHAR(20)';				$field_block_0_field_14->uitype = 10; 				$field_block_0_field_14->typeofdata = 'V~M';				$block_0_->addField($field_block_0_field_14); 				$field_block_0_field_14->setRelatedModules(Array('XActivityType'));			
				$field_block_0_field_15 = new Vtiger_Field();				$field_block_0_field_15->label = 'Workplan Entry';				$field_block_0_field_15->name = 'z_ac_workplanentry';				$field_block_0_field_15->column = 'z_ac_workplanentry';				$field_block_0_field_15->columntype = 'VARCHAR(20)';				$field_block_0_field_15->uitype = 10; 				$field_block_0_field_15->typeofdata = 'V~O';				$block_0_->addField($field_block_0_field_15); 				$field_block_0_field_15->setRelatedModules(Array('XWorkplanEntry'));			
				$field_block_0_field_16 = new Vtiger_Field();				$field_block_0_field_16->label = 'Customer';				$field_block_0_field_16->name = 'z_ac_customer';				$field_block_0_field_16->column = 'z_ac_customer';				$field_block_0_field_16->columntype = 'VARCHAR(20)';				$field_block_0_field_16->uitype = 10; 				$field_block_0_field_16->typeofdata = 'V~M';				$block_0_->addField($field_block_0_field_16); 				$field_block_0_field_16->setRelatedModules(Array('XCustomer'));			
				$field_block_0_field_17 = new Vtiger_Field();				$field_block_0_field_17->label = 'First Time Visit';				$field_block_0_field_17->name = 'z_ac_firsttimevisit';				$field_block_0_field_17->column = 'z_ac_firsttimevisit';				$field_block_0_field_17->columntype = 'VARCHAR(3)';				$field_block_0_field_17->uitype = 56; 				$field_block_0_field_17->typeofdata = 'C~O';				$block_0_->addField($field_block_0_field_17); 			
				$field_block_0_field_18 = new Vtiger_Field();				$field_block_0_field_18->label = 'Planned Visit';				$field_block_0_field_18->name = 'z_ac_plannedvisit';				$field_block_0_field_18->column = 'z_ac_plannedvisit';				$field_block_0_field_18->columntype = 'VARCHAR(3)';				$field_block_0_field_18->uitype = 56; 				$field_block_0_field_18->typeofdata = 'C~O';				$block_0_->addField($field_block_0_field_18); 			 
	$block_1_ = new Vtiger_Block();	$block_1_->label = 'With CoSMRs';	$module->addBlock($block_1_);
				$field_block_1_field_1 = new Vtiger_Field();				$field_block_1_field_1->label = 'SMR';				$field_block_1_field_1->name = 'z_ac_smr';				$field_block_1_field_1->column = 'z_ac_smr';				$field_block_1_field_1->columntype = 'VARCHAR(20)';				$field_block_1_field_1->uitype = 10; 				$field_block_1_field_1->typeofdata = 'V~O';				$block_1_->addField($field_block_1_field_1); 				$field_block_1_field_1->setRelatedModules(Array('XSMR'));			 
	$block_2_ = new Vtiger_Block();	$block_2_->label = 'DIY or Supermarket';	$module->addBlock($block_2_);
				$field_block_2_field_1 = new Vtiger_Field();				$field_block_2_field_1->label = 'Issues Identified';				$field_block_2_field_1->name = 'z_ac_issuesidentified';				$field_block_2_field_1->column = 'z_ac_issuesidentified';				$field_block_2_field_1->columntype = 'TEXT';				$field_block_2_field_1->uitype = 21; 				$field_block_2_field_1->typeofdata = 'V~O';				$block_2_->addField($field_block_2_field_1); 			
				$field_block_2_field_2 = new Vtiger_Field();				$field_block_2_field_2->label = 'Feedback From Customer';				$field_block_2_field_2->name = 'z_ac_feedbackfromcu';				$field_block_2_field_2->column = 'z_ac_feedbackfromcu';				$field_block_2_field_2->columntype = 'TEXT';				$field_block_2_field_2->uitype = 21; 				$field_block_2_field_2->typeofdata = 'V~O';				$block_2_->addField($field_block_2_field_2); 			
				$field_block_2_field_3 = new Vtiger_Field();				$field_block_2_field_3->label = 'Ongoing Campaigns';				$field_block_2_field_3->name = 'z_ac_ongoingcampaigns';				$field_block_2_field_3->column = 'z_ac_ongoingcampaigns';				$field_block_2_field_3->columntype = 'TEXT';				$field_block_2_field_3->uitype = 21; 				$field_block_2_field_3->typeofdata = 'V~O';				$block_2_->addField($field_block_2_field_3); 			 
	$block_3_ = new Vtiger_Block();	$block_3_->label = 'Retail Visit';	$module->addBlock($block_3_);
				$field_block_3_field_1 = new Vtiger_Field();				$field_block_3_field_1->label = 'Last Delivery';				$field_block_3_field_1->name = 'z_ac_lastdelivery';				$field_block_3_field_1->column = 'z_ac_lastdelivery';				$field_block_3_field_1->columntype = 'TEXT';				$field_block_3_field_1->uitype = 21; 				$field_block_3_field_1->typeofdata = 'V~O';				$block_3_->addField($field_block_3_field_1); 			
				$field_block_3_field_2 = new Vtiger_Field();				$field_block_3_field_2->label = 'Promo Stubs Details';				$field_block_3_field_2->name = 'z_ac_promostubsdetails';				$field_block_3_field_2->column = 'z_ac_promostubsdetails';				$field_block_3_field_2->columntype = 'TEXT';				$field_block_3_field_2->uitype = 21; 				$field_block_3_field_2->typeofdata = 'V~O';				$block_3_->addField($field_block_3_field_2); 			 
	$block_4_ = new Vtiger_Block();	$block_4_->label = 'Project Visit';	$module->addBlock($block_4_);
				$field_block_4_field_1 = new Vtiger_Field();				$field_block_4_field_1->label = 'Project Name';				$field_block_4_field_1->name = 'z_ac_projectname';				$field_block_4_field_1->column = 'z_ac_projectname';				$field_block_4_field_1->columntype = 'VARCHAR(100)';				$field_block_4_field_1->uitype = 1; 				$field_block_4_field_1->typeofdata = 'V~O~LE~100';				$block_4_->addField($field_block_4_field_1); 			
				$field_block_4_field_2 = new Vtiger_Field();				$field_block_4_field_2->label = 'Project Stage';				$field_block_4_field_2->name = 'z_ac_projectstage';				$field_block_4_field_2->column = 'z_ac_projectstage';				$field_block_4_field_2->columntype = 'VARCHAR(255)';				$field_block_4_field_2->uitype = 15; 				$field_block_4_field_2->typeofdata = 'V~O';				$block_4_->addField($field_block_4_field_2); 				$field_block_4_field_2->setPicklistValues(Array('- Select -'));			
				$field_block_4_field_3 = new Vtiger_Field();				$field_block_4_field_3->label = 'Project Category';				$field_block_4_field_3->name = 'z_ac_projectcategory';				$field_block_4_field_3->column = 'z_ac_projectcategory';				$field_block_4_field_3->columntype = 'VARCHAR(255)';				$field_block_4_field_3->uitype = 15; 				$field_block_4_field_3->typeofdata = 'V~O';				$block_4_->addField($field_block_4_field_3); 				$field_block_4_field_3->setPicklistValues(Array('- Select -'));			 
	$block_5_ = new Vtiger_Block();	$block_5_->label = 'Trainings';	$module->addBlock($block_5_);
				$field_block_5_field_1 = new Vtiger_Field();				$field_block_5_field_1->label = 'Date';				$field_block_5_field_1->name = 'z_ac_date';				$field_block_5_field_1->column = 'z_ac_date';				$field_block_5_field_1->columntype = 'DATE';				$field_block_5_field_1->uitype = 5; 				$field_block_5_field_1->typeofdata = 'D~O';				$block_5_->addField($field_block_5_field_1); 			
				$field_block_5_field_2 = new Vtiger_Field();				$field_block_5_field_2->label = 'Time';				$field_block_5_field_2->name = 'z_ac_time';				$field_block_5_field_2->column = 'z_ac_time';				$field_block_5_field_2->columntype = 'VARCHAR(100)';				$field_block_5_field_2->uitype = 1; 				$field_block_5_field_2->typeofdata = 'V~O~LE~100';				$block_5_->addField($field_block_5_field_2); 			
				$field_block_5_field_3 = new Vtiger_Field();				$field_block_5_field_3->label = 'Venue';				$field_block_5_field_3->name = 'z_ac_venue';				$field_block_5_field_3->column = 'z_ac_venue';				$field_block_5_field_3->columntype = 'VARCHAR(255)';				$field_block_5_field_3->uitype = 15; 				$field_block_5_field_3->typeofdata = 'V~O';				$block_5_->addField($field_block_5_field_3); 				$field_block_5_field_3->setPicklistValues(Array('- Select -'));			
				$field_block_5_field_4 = new Vtiger_Field();				$field_block_5_field_4->label = 'Number of Attendees';				$field_block_5_field_4->name = 'z_ac_noofattenees';				$field_block_5_field_4->column = 'z_ac_noofattenees';				$field_block_5_field_4->columntype = 'VARCHAR(255)';				$field_block_5_field_4->uitype = 15; 				$field_block_5_field_4->typeofdata = 'V~O';				$block_5_->addField($field_block_5_field_4); 				$field_block_5_field_4->setPicklistValues(Array('- Select -'));				$filter1 = new Vtiger_Filter();    $filter1->name = 'All';    $filter1->isdefault = true;    $module->addFilter($filter1);    // Add fields to the filter created    $filter1->addField($field_block_0_field_0)->addField($field_block_0_field_1)->addField($field_block_0_field_2)->addField($field_block_0_field_3)->addField($field_block_0_field_4)->addField($field_block_0_field_5)->addField($field_block_0_field_6)->addField($field_block_0_field_7)->addField($field_block_0_field_8)->addField($field_block_0_field_9);        /** Associate other modules to this module */    //$module->setRelatedList(Vtiger_Module::getInstance('Leads'), 'Leads', Array('SELECT'));        /** Set sharing access of this module */    //$module->setDefaultSharing('Private');        /** Enable and Disable available tools */    $module->enableTools(Array('Import', 'Export'));    $module->disableTools('Merge');?>